name: CI

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 10.190.4.6 >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      run: |
        pwd
        echo 'Running ansible-playbook...'
        ansible-playbook playbook.yml -i inventory --extra-vars "ansibleuser=lew ansiblepass=${{ secrets.ADMIN_PASSWORD }}
        azure_client_id=${{ secrets.ARM_CLIENT_ID }} azure_secret=${{ secrets.ARM_CLIENT_SECRET }} azure_tenant=${{ secrets.ARM_TENANT_ID }}"
      working-directory: ansible
