---
- name: Install and Configure Apache Web Server
  hosts: all
  become: yes

  tasks:
    - name: Ensure system is up-to-date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a simple HTML file
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
            <title>Welcome to Apache!</title>
          </head>
          <body>
            <h1>Success! The Apache web server is installed and running.</h1>
          </body>
          </html>
