- name: Basic configuration for all servers
  hosts: all
  tasks:
    - name: ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: ensure known_hosts file exists
      file:
        path: ~/.ssh/known_hosts
        state: touch
        mode: '0644'

    - name: check if known_hosts contains server's fingerprint
      shell: grep -q "$(ssh-keyscan -T5 10.190.4.6)" ~/.ssh/known_hosts || echo "not found"
      register: known_hosts_check
      changed_when: known_hosts_check.stdout != "not found"

    - name: fetch remote ssh key
      command: ssh-keyscan -T5 10.190.4.6
      register: ssh_keyscan_result
      failed_when: ssh_keyscan_result.rc != 0 and ssh_keyscan_result.stdout == ""
