---
- name: Install Azure CLI
  hosts: all
  become: yes

  tasks:
    - name: Ensure system is up-to-date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Python and pip
      apt:
        name: 
          - python3
          - python3-pip
        state: present

    - name: Install Ansible using pip
      pip:
        name: ansible
        state: present

    - name: Install lsb-release
      apt:
        name: lsb-release
        state: present

    - name: Add Microsoft repository key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Microsoft repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Azure CLI
      apt:
        name: azure-cli
        state: present
